variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

stages:
  - Build
  - Publish

build:
  stage: Build
  image: aldgateventuresbot/deploy
  services:
    - docker:19.03.2-dind
  script:
    - build
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/pkgs
  only:
    - branches

publish:
  stage: Publish
  image: aldgateventuresbot/deploy
  script:
    - release
    - publish
  only:
    - master

.functions: &functions |
  set -x

  function new_version {
    local currentVersion
    local newVersion
    local commitDesc=$CI_COMMIT_DESCRIPTION

    if [[ $(git tag) == "" ]]; then
      newVersion="0.1.0"
    else
      currentVersion=$(git ls-remote -q --tags https://${GITHUB_TOKEN}:@github.com/${CI_PROJECT_PATH} | sort -t / -k 3 -V | grep -v '{}' | tail -n 1 | awk -F / '{print $3}')

      case $commitDesc in
        *+bump-major*)
          newVersion=$(/usr/local/bin/semver bump major $currentVersion)
          ;;
        *+bump-minor*)
          newVersion=$(/usr/local/bin/semver bump minor $currentVersion)
          ;;
        *)
          newVersion=$(/usr/local/bin/semver bump patch $currentVersion)
          ;;
      esac
    fi

    echo $newVersion
  }

  function build() {
    newVersion=$(new_version)
    mkdir pkgs
    docker run -v $PWD:/build aldgateventuresbot/c-crosscompile sh -c "cd /build && \
    make && \
    cd android && \
    echo 'ndk.dir=/opt/android-ndk' > local.properties && \
    ./gradlew assemble && \
    cd /build/ && \
    for arch in arm64-v8a armeabi-v7a x86 x86_64; do \
      mkdir -p \"/build/self-olm-android-\$arch/include/self_olm\" && \
      mv \"android/olm-sdk/src/main/libs/\$arch/libself_olm.so\" \"android/olm-sdk/src/main/libs/\$arch/libsodium.so\" \"/build/self-olm-android-\$arch/\" && \
      cp include/self_olm/olm.h include/self_olm/outbound_group_session.h include/self_olm/inbound_group_session.h include/self_olm/pk.h include/self_olm/sas.h \"/build/self-olm-android-\$arch/include/self_olm\" && \
      tar -zcvf \"/build/pkgs/libself-olm-$newVersion-android-\$arch.tar.gz\" \"self-olm-android-\$arch\"; \
    done"

    docker run -v $PWD:/build aldgateventuresbot/fpm sh -c "apt-get update && \
    apt-get install -y libsodium-dev rpm && \
    cd /build && \
    mkdir -p self-olm-linux-x86_64/include/self_olm/ && \
    cp include/self_olm/olm.h include/self_olm/outbound_group_session.h include/self_olm/inbound_group_session.h include/self_olm/pk.h include/self_olm/sas.h /build/self-olm-linux-x86_64/include/self_olm && \
    cp ./build/libself_olm.so ./build/libself_olm.so.3 ./build/libself_olm.so.3.1.4 /build/self-olm-linux-x86_64 && \
    tar -zcvf /build/pkgs/libself-olm-$newVersion-linux-x86_64.tar.gz self-olm-linux-x86_64 && \
    fpm -s dir -t deb -n libself-olm -v ${newVersion} -p pkgs --deb-no-default-config-files -d libsodium-dev ./build/libself_olm.so=/usr/lib/ ./build/libself_olm.so.3=/usr/lib/ ./build/libself_olm.so.3.1.4=/usr/lib/ ./include/self_olm/=/usr/include/self_olm && \
    fpm -s dir -t rpm -n libself-olm -v ${newVersion} -p pkgs -d libsodium-devel ./build/libself_olm.so=/usr/lib/ ./build/libself_olm.so.3=/usr/lib/ ./build/libself_olm.so.3.1.4=/usr/lib/ ./include/self_olm/=/usr/include/self_olm"
  }

  function setup_git() {
    git config --global user.name self-ci-bot
    git config --global user.email ops@selfid.net
    git config --global url."https://${GITHUB_TOKEN}:@github.com".insteadOf "https://github.com"
  }

  function release() {
    newVersion=$(new_version)
    setup_git
    git remote set-url origin https://${GITHUB_TOKEN}:@github.com/${CI_PROJECT_PATH}
    git_release $newVersion
    slack_notify $newVersion
  }

  function git_release() {
    version=$1
    git tag -a $version -m "$version"
    git push origin $version
  }

  function publish() {
    echo $GCP_SA_CI | base64 -d > /tmp/gcp-sa-ci.json
    gcloud auth activate-service-account --key-file /tmp/gcp-sa-ci.json
    gsutil cp pkgs/libself-olm* gs://download.selfid.net/olm
  }

  function slack_notify() {
    version=$1
    slack chat send "New release <https://github.com/${CI_PROJECT_PATH}|${CI_PROJECT_NAME}> <https://github.com/${CI_PROJECT_PATH}/commits/${version}|${version}>" '#ci'
  }

before_script:
  - *functions
