variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

stages:
  - Build

build:
  stage: Build
  image: docker:stable-git
  services:
    - docker:19.03.2-dind
  script:
    - build
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/pkgs
  only:
    - branches

.functions: &functions |
  set -x

  function new_version {
    local x="foo"
    #echo "-------------------------- $x - func ----------------------------"
    echo $x
  }



  function build() {
    echo "------------------------- ${x} - build --------------------------------------"
    local newx=$(new_version)
    echo "------------------------- ${newx} - build --------------------------------------"

  }

before_script:
  - *functions
