variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

stages:
  - Build
  - Publish

build:
  stage: Build
  image: docker:stable-git
  services:
    - docker:19.03.2-dind
  script:
    - build
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/pkgs
  only:
    - branches

publish:
  stage: Publish
  image: aldgateventuresbot/deploy
  script:
    - ls -lah
  only:
    - branches

.functions: &functions |
  set -x

  function new_version {
    commitDesc=$CI_COMMIT_DESCRIPTION

    if [[ $(git tag) == "" ]]; then
      newVersion="0.1.0"
    else
      currentVersion=$(git ls-remote -q --tags https://${GITHUB_TOKEN}:@github.com/${CI_PROJECT_PATH} | sort -t / -k 3 -V | grep -v '{}' | tail -n 1 | awk -F / '{print $3}')

      case $commitDesc in
        *+bump-major*)
          newVersion=$(semver bump major $currentVersion)
          ;;
        *+bump-minor*)
          newVersion=$(semver bump minor $currentVersion)
          ;;
        *)
          newVersion=$(semver bump patch $currentVersion)
          ;;
      esac
    fi

    echo "-------------------- ${newVersion} ----------------"
    

  }

  function build() {
    #new_version
    echo "============== ${newVersion} ================="
  }

before_script:
  - *functions
